name: Add Missing text-domain

on:
  push:
    branches:
      - dev

jobs:
  WP_Text_Domain:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: WordPress Textdomain
      uses: varunsridharan/action-wp-textdomain@1.1
      with:
        domain: 'wp-github-action'
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
